### ISSUE TITLE
Feature request: Customization option for messages?

### ISSUE THREAD

**Issue by Andre601** [PuneetGopinath/github-activity-readme#7]
Please check these things before submitting your issue:

- [x] I searched for duplicate or closed feature request [here](https://github.com/PuneetGopinath/github-activity-readme/issues?q=is%3Aissue)

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I saw through the [Active GitHub Forks page](https://techgaun.github.io/active-forks/index.html#jamesgeorge007/github-activity-readme) that this fork seems to be the most active and up to date one, so I post my feature request here in the hope it will be looked into.

The idea is, to allow the customization of the different action messages to give a bit more creativity.

As an example, imagine the following configuration setup:
```yaml
    steps:
      - uses: actions/checkout@v2
      - uses: PuneetGopinath/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "Update latest activities 🎉"
          
          # Comments
          COMMENT: "Commented on [`{REPO}#{ID}`]({URL})"
          
          # Pull requests
          PR_OPEN: "Opened Pull request [`{REPO}#{ID}`]({URL})"
          PR_CLOSE: "Closed Pull request [`{REPO}#{ID}`]({URL})"
          PR_MERGE: "Merged Pull request [`{REPO}#{ID}`]({URL})"
          
          # Issues
          ISSUE_OPEN: "Opened Issue [`{REPO}#{ID}`]({URL})"
          ISSUE_CLOSE: "Closed Issue [`{REPO}#{ID}`]({URL})"
```

You can see some `{PLACEHOLDER}` text there. They would do the following things:

- `{REPO}`
  Will be changed to the `Username/Repository` format (i.e. Andre601/Andre601).
- `{ID}`
  Will be changed to the issue, PR or Discussion ID this action belongs to.
- `{URL}`
  Will be changed to the URL to view the issue, PR or Discussion.

The above configuration would result in the following results being displayed:

1. Opened Issue [`PuneetGopinath/github-activity-readme#7`](https://github.com/PuneetGopinath/github-activity-readme/issue/7)
2. Closed Pull request [`PuneetGopinath/github-activity-readme#3`](https://github.com/PuneetGopinath/github-activity-readme/pull/3)
3. Merged Pull request [`PuneetGopinath/github-activity-readme#6`](https://github.com/PuneetGopinath/github-activity-readme/pull/6)
4. Opened Pull request [`PuneetGopinath/github-activity-readme#3`](https://github.com/PuneetGopinath/github-activity-readme/pull/3)
5. Opened Pull request [`PuneetGopinath/github-activity-readme#6`](https://github.com/PuneetGopinath/github-activity-readme/pull/6)

**Describe alternatives you've considered**
Only alternative would be to fork this and implement the changes myself, but I lack the knowledge to achieve this, so I won't risk anything here.

**Additional context**
